/* After AIMP, some tracks were "Harris Heller - ", so to remove that:
`get-childitem *.ogg | foreach { echo $_; rename-item $_ $_.Name.Replace("Harris Heller - ", ""); }`
`for($num = 99; $num -gt 0; $num--) { get-childitem *.ogg | foreach { if ($_.Name.startsWith("$($num). ")) { rename-item $_ $_.Name.Replace("$($num). ", ""); } } }`
And to list all stuff, classic cmd:
`dir /b`
*/

const list_of_names_version = 1; // UPDATE WHEN LIST IS CHANGED!
const list_of_names_index = [ // list of tracks
    "576, from Album 3. Sakura Dreams.ogg",
    "90_s, from Album 2. Fantasy Arcade.ogg",
    "A Moment Suspended, from Album 17. Electric.ogg",
    "A Nomad_s Way, from Album 3. Sakura Dreams.ogg",
    "A Passion For Glory, from Album 7. Gold.ogg",
    "Absolutely Zero Cares, from Album 14. Neon.ogg",
    "Afternoon Delight, from Album 14. Neon.ogg",
    "Afternoon Drift, from Album 17. Electric.ogg",
    "Aging Juniper, from Album 15. Quest.ogg",
    "Ain_t No Rest For The Stars, from Album 1. High At The Planetarium.ogg",
    "Akita Inu, from Album 9. Inu.ogg",
    "All the Right Moves, from Album 4. In 4k.ogg",
    "All The Royalties, from Album 9. Inu.ogg",
    "Amber Afterglow, from Album 19. Prime.ogg",
    "Amber Leaves, from Album 20. Slaps.ogg",
    "Ambient Gold, from Album 7. Gold.ogg",
    "Ambient Gold, from Album Single - Ambient Gold.ogg",
    "Ambrosia Cascade, from Album 12. Cherry Soda.ogg",
    "Andromeda Skies, from Album 1. High At The Planetarium.ogg",
    "Anime and Chill, from Album 9. Inu.ogg",
    "Another Castle, from Album 2. Fantasy Arcade.ogg",
    "Another World, from Album 1. High At The Planetarium.ogg",
    "Antique Rose, from Album 14. Neon.ogg",
    "Anytime, from Album 12. Cherry Soda.ogg",
    "Apollo Appetite, from Album 13. Reflection_.ogg",
    "Aquamorena, from Album 7. Gold.ogg",
    "Are You Still There, from Album 2. Fantasy Arcade.ogg",
    "Arriving at Nowhere, from Album 6. Certain Shade Of Blue.ogg",
    "Ashes, from Album 14. Neon.ogg",
    "Aurora Sonata, from Album 6. Certain Shade Of Blue.ogg",
    "Aurora, from Album 1. High At The Planetarium.ogg",
    "Autumn Hues, from Album 18. Moonwalk.ogg",
    "Backtracking, from Album 5. Ocularium.ogg",
    "Bamboo Shampoo, from Album 11. Rain.ogg",
    "Banana Fuego, from Album 9. Inu.ogg",
    "Basement Tan, from Album 8. White.ogg",
    "Basking Turtles, from Album 14. Neon.ogg",
    "Be My Pegasus, from Album 9. Inu.ogg",
    "Beach Flavored Sand, from Album 9. Inu.ogg",
    "Beach walk, from Album 5. Ocularium.ogg",
    "Beauty for Sale, from Album 8. White.ogg",
    "Because Rain, from Album 4. In 4k.ogg",
    "Because You Asked, from Album 4. In 4k.ogg",
    "Beyond The Clouds, from Album 1. High At The Planetarium.ogg",
    "Big Blue, from Album 2. Fantasy Arcade.ogg",
    "Big City, from Album 16. Secluded.ogg",
    "Bleeding Road, from Album 6. Certain Shade Of Blue.ogg",
    "Blown Over, from Album 20. Slaps.ogg",
    "Blue Mint Road, from Album 14. Neon.ogg",
    "Blue River Temple, from Album 3. Sakura Dreams.ogg",
    "Blue Waves, from Album 15. Quest.ogg",
    "Blue Yellow Sky, from Album 4. In 4k.ogg",
    "Bokeh, from Album 10. Neko.ogg",
    "Bokeh, from Album 12. Cherry Soda.ogg",
    "BRB, from Album Ocularium.ogg",
    "Breezy, from Album 11. Rain.ogg",
    "Bucket List, from Album 8. White.ogg",
    "Buffering, from Album 9. Inu.ogg",
    "Business As Usual, from Album 5. Ocularium.ogg",
    "Butterfly Effect, from Album 1Rain.ogg",
    "Cafe Corner, from Album 17. Electric.ogg",
    "Call Me Daddy, from Album 10. Neko.ogg",
    "Call, from Album 7. Gold.ogg",
    "Calling California, from Album 7. Gold.ogg",
    "Calling the Sun, from Album 5. Ocularium.ogg",
    "Calm Waters, from Album 9. Inu.ogg",
    "Camouflaged Underneath, from Album 16. Secluded.ogg",
    "Careless, from Album 8. White.ogg",
    "Carousel, from Album 4. In 4k.ogg",
    "Carousel, from Album 6. Certain Shade Of Blue.ogg",
    "Carriage Rides, from Album 19. Prime.ogg",
    "Castle Cream, from Album 19. Prime.ogg",
    "Celestial Journeys, from Album 19. Prime.ogg",
    "Celestial Reverb, from Album 1. High At The Planetarium.ogg",
    "Celestial Rewind, from Album 7. Gold.ogg",
    "Charismatic Fountains, from Album 13. Reflection_.ogg",
    "Charlie Chaplin, from Album 8. White.ogg",
    "Charming Smile, from Album 19. Prime.ogg",
    "Cheating Heart, from Album 20. Slaps.ogg",
    "Cherry Blossom Skies, from Album 3. Sakura Dreams.ogg",
    "Cherry Blossoms, from Album 19. Prime.ogg",
    "Child_s Play, from Album 5. Ocularium.ogg",
    "Chill Waves, from Album 18. Moonwalk.ogg",
    "Chillout in the Cosmos, from Album 17. Electric.ogg",
    "Chimes, from Album 7. Gold.ogg",
    "Cielo, from Album 11. Rain.ogg",
    "Cinnamon Sugar Bun, from Album 14. Neon.ogg",
    "Cityscape Lullabies, from Album 18. Moonwalk.ogg",
    "Classic Look, from Album 14. Neon.ogg",
    "Clay Mountains, from Album 15. Quest.ogg",
    "Clean Slate Again, from Album 14. Neon.ogg",
    "Climax, from Album 16. Secluded.ogg",
    "Cloudy Grey, from Album 14. Neon.ogg",
    "Cloudy Thoughts, from Album 11. Rain.ogg",
    "Clyde, from Album 2. Fantasy Arcade.ogg",
    "Coastal Chimney, from Album 20. Slaps.ogg",
    "Cobbled Streets, from Album 17. Electric.ogg",
    "Coconut Husks, from Album 13. Reflection_.ogg",
    "Coffee and You, from Album 16. Secluded.ogg",
    "Coffee Nook, from Album 19. Prime.ogg",
    "Colestown, from Album 12. Cherry Soda.ogg",
    "Color Field, from Album 12. Cherry Soda.ogg",
    "Consciousness, from Album 5. Ocularium.ogg",
    "Copper Vein, from Album 13. Reflection_.ogg",
    "Cottage Grove, from Album 13. Reflection_.ogg",
    "Countryside Drive, from Album 15. Quest.ogg",
    "Cozy Up, from Album 15. Quest.ogg",
    "Creamy Tea, from Album 1Quest.ogg",
    "Creator_s Kingdom, from Album 6. Certain Shade Of Blue.ogg",
    "Crimson Skies, from Album 18. Moonwalk.ogg",
    "Crystal Garden, from Album 3. Sakura Dreams.ogg",
    "Cutting Rain Drops, from Album 3. Sakura Dreams.ogg",
    "Danger Dance, from Album 10. Neko.ogg",
    "Dark Matter, from Album 1. High At The Planetarium.ogg",
    "Dark Moon, from Album 20. Slaps.ogg",
    "Dawns Early Light, from Album 17. Electric.ogg",
    "Day Dreaming, from Album 11. Rain.ogg",
    "Day You Left, from Album 4. In 4k.ogg",
    "Daylily, from Album 19. Prime.ogg",
    "Daze, from Album 7. Gold.ogg",
    "Deafening Silence, from Album 6. Certain Shade Of Blue.ogg",
    "Death_s Embrace, from Album 3. Sakura Dreams.ogg",
    "Deep Water Dive, from Album 19. Prime.ogg",
    "Deepwater, from Album 1. High At The Planetarium.ogg",
    "Deja Vu, from Album 5. Ocularium.ogg",
    "Desert View, from Album 13. Reflection_.ogg",
    "Desync, from Album 2. Fantasy Arcade.ogg",
    "Devil_s Ivy, from Album 15. Quest.ogg",
    "Dewdrop Dawn, from Album 17. Electric.ogg",
    "Digital Threat, from Album 2. Fantasy Arcade.ogg",
    "Dim Lights, from Album 4. In 4k.ogg",
    "Dippin_, from Album 8. White.ogg",
    "Dissonant Whispers, from Album 5. Ocularium.ogg",
    "Distance, from Album 1. High At The Planetarium.ogg",
    "Distant Rendering, from Album 5. Ocularium.ogg",
    "Doin_ Fine, from Album 11. Rain.ogg",
    "Don_t Fall For Me, from Album 9. Inu.ogg",
    "Double Tree, from Album 20. Slaps.ogg",
    "Dove Love, from Album 13. Reflection_.ogg",
    "Dream About You, from Album 14. Neon.ogg",
    "Dream Weaver, from Album 17. Electric.ogg",
    "Dreams of Dusk, from Album 17. Electric.ogg",
    "Dreary Summer, from Album 4. In 4k.ogg",
    "Drifted Wind, from Album 3. Sakura Dreams.ogg",
    "Dusty Memories, from Album 18. Moonwalk.ogg",
    "Dusty Skyy, from Album 10. Neko.ogg",
    "Earl Gray Morning, from Album 20. Slaps.ogg",
    "Eastern Sunrise, from Album 3. Sakura Dreams.ogg",
    "Echo in the Mountain, from Album 3. Sakura Dreams.ogg",
    "Eclipse Embrace, from Album 17. Electric.ogg",
    "Elemental, from Album 14. Neon.ogg",
    "Endless Drift, from Album 1. High At The Planetarium.ogg",
    "Enjoy the Little Things, from Album 5. Ocularium.ogg",
    "Equilibrium, from Album 5. Ocularium.ogg",
    "Eros Love, from Album 20. Slaps.ogg",
    "Ether, from Album 2. Fantasy Arcade.ogg",
    "Ethereal Echoes, from Album 18. Moonwalk.ogg",
    "Euphoria, from Album 6. Certain Shade Of Blue.ogg",
    "Evening Breeze, from Album 17. Electric.ogg",
    "Evergreen Forest, from Album 20. Slaps.ogg",
    "Faded Days, from Album 4. In 4k.ogg",
    "Faded Jeans, from Album 16. Secluded.ogg",
    "Faded Memories, from Album 3. Sakura Dreams.ogg",
    "Fading Frequencies, from Album 19. Prime.ogg",
    "Fading Sunrise, from Album 20. Slaps.ogg",
    "Fall With Me, from Album 10. Neko.ogg",
    "Falling Up, from Album 8. White.ogg",
    "Fallin_ Over Spring, from Album 13. Reflection_.ogg",
    "Farm Lands, from Album 3. Sakura Dreams.ogg",
    "Fashionably Late_, from Album 13. Reflection_.ogg",
    "Field Harvesting, from Album 15. Quest.ogg",
    "Firefly Nights, from Album 11. Rain.ogg",
    "First Light, from Album 13. Reflection_.ogg",
    "Floating Soul, from Album 1. High At The Planetarium.ogg",
    "Fluffy Cotton, from Album 19. Prime.ogg",
    "Flute of the Traveler, from Album 3. Sakura Dreams.ogg",
    "Fly Me High, from Album 4. In 4k.ogg",
    "Forever Young with You, from Album 13. Reflection_.ogg",
    "Forget the Past, from Album 4. In 4k.ogg",
    "Fox Glare, from Album 13. Reflection_.ogg",
    "French Pastries, from Album 19. Prime.ogg",
    "Fresh Looks, from Album 15. Quest.ogg",
    "Frontier, from Album 4. In 4k.ogg",
    "Frosted Rose, from Album 13. Reflection_.ogg",
    "Frozen Rain, from Album 11. Rain.ogg",
    "Furby, from Album 12. Cherry Soda.ogg",
    "Further, from Album 1. High At The Planetarium.ogg",
    "Galaxy, from Album 11. Rain.ogg",
    "Gazes, from Album 4. In 4k.ogg",
    "Geisha_s Lament, from Album 3. Sakura Dreams.ogg",
    "Gentle Gradients, from Album 17. Electric.ogg",
    "Georgia Paradise, from Album 16. Secluded.ogg",
    "Ghost in the Daylight, from Album 3. Sakura Dreams.ogg",
    "Gift for a Thrill, from Album 8. White.ogg",
    "Glass And Water, from Album 10. Neko.ogg",
    "Gloomy Grooves, from Album 18. Moonwalk.ogg",
    "Glorifier, from Album 6. Certain Shade Of Blue.ogg",
    "Glow Worm_, from Album 16. Secluded.ogg",
    "Glowing, from Album 9. Inu.ogg",
    "Gold Rush Canyon, from Album 15. Quest.ogg",
    "Golden Age, from Album 3. Sakura Dreams.ogg",
    "Golden Hour Love, from Album 18. Moonwalk.ogg",
    "Gone, from Album 1. High At The Planetarium.ogg",
    "Good Day feels, from Album 13. Reflection_.ogg",
    "Gradient Eclipse, from Album 1. High At The Planetarium.ogg",
    "Green Giant Canopy, from Album 15. Quest.ogg",
    "Green Leaves, from Album 10. Neko.ogg",
    "Green Ripple, from Album 20. Slaps.ogg",
    "Guilty Spark, from Album 2. Fantasy Arcade.ogg",
    "Gum Drop, from Album 12. Cherry Soda.ogg",
    "Gummy Bears, from Album 11. Rain.ogg",
    "Gusty Glade, from Album 2. Fantasy Arcade.ogg",
    "Hard Tan Lines, from Album 13. Reflection_.ogg",
    "Harmonic Diddles, from Album 17. Electric.ogg",
    "Harris Heller -Tequila Night, from Album 16. Secluded.ogg",
    "Hazel Way, from Album 20. Slaps.ogg",
    "Hazy Monicle, from Album 19. Prime.ogg",
    "HD Reverse, from Album 10. Neko.ogg",
    "Heading Out Nowhere, from Album 5. Ocularium.ogg",
    "Headspace, from Album 7. Gold.ogg",
    "Healing Salve, from Album 16. Secluded.ogg",
    "Heart Piece, from Album 2. Fantasy Arcade.ogg",
    "Hella Fresh, from Album 6. Certain Shade Of Blue.ogg",
    "Heroes Never Die, from Album 2. Fantasy Arcade.ogg",
    "Hidden Alley Harmonies, from Album 17. Electric.ogg",
    "Hidden Meadow_new, from Album Rain.ogg",
    "Hideaway for Now, from Album 16. Secluded.ogg",
    "High Tide, from Album 14. Neon.ogg",
    "Highway Nights, from Album 11. Rain.ogg",
    "Hillside Morning, from Album 13. Reflection_.ogg",
    "Hint of Lime, from Album 14. Neon.ogg",
    "Hiro, from Album 3. Sakura Dreams.ogg",
    "Home At Last, from Album 20. Slaps.ogg",
    "Homebody, from Album 15. Quest.ogg",
    "Honey Hips, from Album 10. Neko.ogg",
    "Honey Juice, from Album 1Secluded.ogg",
    "Honey Lights, from Album 4. In 4k.ogg",
    "Honolulu, from Album 10. Neko.ogg",
    "Humble, from Album 5. Ocularium.ogg",
    "Huntress, from Album 5. Ocularium.ogg",
    "I Know I Lied, from Album 9. Inu.ogg",
    "I Want To Believe, from Album 10. Neko.ogg",
    "Ice On My Tongue, from Album 9. Inu.ogg",
    "Iceberg Ahead, from Album 13. Reflection_.ogg",
    "In Bloom, from Album 19. Prime.ogg",
    "In My Shadow, from Album 1. High At The Planetarium.ogg",
    "Indigo Ideas, from Album 20. Slaps.ogg",
    "Innocence, from Album 8. White.ogg",
    "Into The Void, from Album 7. Gold.ogg",
    "Iridescent, from Album 6. Certain Shade Of Blue.ogg",
    "Iroh_s Tea, from Album 10. Neko.ogg",
    "Is Anybody Out There, from Album 1. High At The Planetarium.ogg",
    "Jacket In The Summer, from Album 4. In 4k.ogg",
    "Jellyfish Bossa, from Album 12. Cherry Soda.ogg",
    "Just Hit Play, from Album 10. Neko.ogg",
    "Kenz, from Album 7. Gold.ogg",
    "Kick It Back, from Album 8. White.ogg",
    "Lake House Hammock, from Album 20. Slaps.ogg",
    "Lake View, from Album 19. Prime.ogg",
    "Last Stop, from Album 12. Cherry Soda.ogg",
    "Late Night Latte, from Album 17. Electric.ogg",
    "Lava Lamp, from Album 12. Cherry Soda.ogg",
    "Lavender Blush, from Album 20. Slaps.ogg",
    "Lavender Tower, from Album 2. Fantasy Arcade.ogg",
    "Lean of Phobia, from Album 6. Certain Shade Of Blue.ogg",
    "Legacy of None, from Album 6. Certain Shade Of Blue.ogg",
    "Lemon Leaves, from Album 13. Reflection_.ogg",
    "Lemon Switchel, from Album 12. Cherry Soda.ogg",
    "Let_s Call Mom, from Album 9. Inu.ogg",
    "Lightwire, from Album 7. Gold.ogg",
    "Lightyears, from Album 4. In 4k.ogg",
    "Lily_s Eyes, from Album 9. Inu.ogg",
    "Lime Soda, from Album 12. Cherry Soda.ogg",
    "Little Light, from Album 2. Fantasy Arcade.ogg",
    "Lone Tree Haze, from Album 15. Quest.ogg",
    "Lost in Perspective, from Album 4. In 4k.ogg",
    "Lost in Thought, from Album 18. Moonwalk.ogg",
    "Lost, from Album 3. Sakura Dreams.ogg",
    "Lucid Dreaming, from Album 5. Ocularium.ogg",
    "Lucky Wednesday, from Album 12. Cherry Soda.ogg",
    "Luna, from Album 13. Reflection_.ogg",
    "Lunar Dust, from Album 1. High At The Planetarium.ogg",
    "Luxe Lie, from Album 20. Slaps.ogg",
    "Macha, from Album 3. Sakura Dreams.ogg",
    "Magnolia Breath, from Album 20. Slaps.ogg",
    "Malibu Drive, from Album 13. Reflection_.ogg",
    "Maneki-neko, from Album 10. Neko.ogg",
    "Manhattan Project, from Album 2. Fantasy Arcade.ogg",
    "Marmalade, from Album 15. Quest.ogg",
    "Marshmellow Pie, from Album 12. Cherry Soda.ogg",
    "Memorized Sunset, from Album 9. Inu.ogg",
    "Memory of You, from Album Certain Shade Of Blue.ogg",
    "Mercury Kid, from Album 12. Cherry Soda.ogg",
    "Meteor Binge, from Album 1. High At The Planetarium.ogg",
    "Midnight Breeze, from Album 18. Moonwalk.ogg",
    "Midnight Stroll, from Album 4. In 4k.ogg",
    "Mint Frost, from Album 9. Inu.ogg",
    "Minuet of the Forest, from Album 2. Fantasy Arcade.ogg",
    "Miramar Sunset, from Album 2. Fantasy Arcade.ogg",
    "Mirrors Don_t Lie, from Album 8. White.ogg",
    "Misty Mornings, from Album 18. Moonwalk.ogg",
    "Monday Murmurs, from Album 18. Moonwalk.ogg",
    "Monday_s Routine, from Album 15. Quest.ogg",
    "Mood Swings, from Album 6. Certain Shade Of Blue.ogg",
    "Moody Fig, from Album 19. Prime.ogg",
    "Moonlit Melancholy, from Album 18. Moonwalk.ogg",
    "Moonrise, from Album 8. White.ogg",
    "Moons of Lylat, from Album Fantasy Arcade.ogg",
    "Moons of Neptune, from Album 1. High At The Planetarium.ogg",
    "Morning Calm, from Album 16. Secluded.ogg",
    "Morning Run, from Album 14. Neon.ogg",
    "Morning Without You, from Album 8. White.ogg",
    "Most Requested, from Album 9. Inu.ogg",
    "Motor Town, from Album 10. Neko.ogg",
    "Mount Never Rest, from Album 5. Ocularium.ogg",
    "Moving Lights, from Album 7. Gold.ogg",
    "Mr. Melatonin, from Album 4. In 4k.ogg",
    "Mute City, from Album 2. Fantasy Arcade.ogg",
    "My Bucket List, from Album 13. Reflection_.ogg",
    "Myrtle Ravine, from Album 19. Prime.ogg",
    "Mysteryland, from Album 6. Certain Shade Of Blue.ogg",
    "N64, from Album Inu.ogg",
    "Natural Lips, from Album 14. Neon.ogg",
    "Nature_s Caress, from Album 16. Secluded.ogg",
    "Neon Drive, from Album 7. Gold.ogg",
    "Neon in the Metropolis, from Album 17. Electric.ogg",
    "Neptune, from Album 9. Inu.ogg",
    "New Road, from Album 3. Sakura Dreams.ogg",
    "Night Market, from Album 3. Sakura Dreams.ogg",
    "Night Roses, from Album 12. Cherry Soda.ogg",
    "Night Shift, from Album 12. Cherry Soda.ogg",
    "Nightfall Narratives, from Album 17. Electric.ogg",
    "Nightshift, from Album 8. White.ogg",
    "No Blue Sky, from Album 9. Inu.ogg",
    "No One_s Hero, from Album 7. Gold.ogg",
    "Nocturnal Eyes, from Album 17. Electric.ogg",
    "Nostalgia, from Album 4. In 4k.ogg",
    "Nostalgic Nights, from Album 18. Moonwalk.ogg",
    "Not Enough Movement, from Album 2. Fantasy Arcade.ogg",
    "Oasis Skyline, from Album 5. Ocularium.ogg",
    "Oat Latte, from Album 12. Cherry Soda.ogg",
    "Obsidian, from Album 8. White.ogg",
    "Ocean Blues, from Album 7. Gold.ogg",
    "Ocean Scent, from Album 4. In 4k.ogg",
    "Oceanic Odyssey, from Album 18. Moonwalk.ogg",
    "Ocha, from Album 3. Sakura Dreams.ogg",
    "October Mist, from Album 20. Slaps.ogg",
    "Ocularium, from Album 5. Ocularium.ogg",
    "Of Course I Still Love You, from Album 5. Ocularium.ogg",
    "Olive Grove, from Album 14. Neon.ogg",
    "On the Wharf , from Album 12. Cherry Soda.ogg",
    "One More Thing, from Album 10. Neko.ogg",
    "One More, from Album 6. Certain Shade Of Blue.ogg",
    "Onsen Dreams, from Album 3. Sakura Dreams.ogg",
    "Opal Lounge, from Album 12. Cherry Soda.ogg",
    "Open Door, from Album 8. White.ogg",
    "Orbis, from Album 9. Inu.ogg",
    "Out of Phase, from Album 7. Gold.ogg",
    "Outside, from Album 4. In 4k.ogg",
    "Over and Over, from Album White.ogg",
    "Oyster Bay, from Album 19. Prime.ogg",
    "Palace Walkways, from Album 16. Secluded.ogg",
    "Palette of Dreams, from Album 19. Prime.ogg",
    "Paralyze the Moment, from Album 6. Certain Shade Of Blue.ogg",
    "Park Time, from Album 15. Quest.ogg",
    "Partial Moonlight, from Album 1. High At The Planetarium.ogg",
    "Path Less Traveled, from Album High At The Planetarium.ogg",
    "Peacekeeper, from Album 2. Fantasy Arcade.ogg",
    "Pearly Whites, from Album 14. Neon.ogg",
    "Pebbled Path, from Album 20. Slaps.ogg",
    "Peel and Stick, from Album 19. Prime.ogg",
    "Pensive Patterns, from Album 17. Electric.ogg",
    "Phendrana Drifts, from Album 2. Fantasy Arcade.ogg",
    "Pillar of Autumn, from Album 2. Fantasy Arcade.ogg",
    "Pipe Dream, from Album 19. Prime.ogg",
    "Pipe Dream, from Album 7. Gold.ogg",
    "Pitch Black, from Album 16. Secluded.ogg",
    "Pixel Sunrise, from Album 4. In 4k.ogg",
    "Plaid, from Album 1. High At The Planetarium.ogg",
    "Platinum Streaks, from Album 14. Neon.ogg",
    "Play It Again, Sam, from Album 10. Neko.ogg",
    "Pleasure Bay, from Album 15. Quest.ogg",
    "Plethora, from Album 6. Certain Shade Of Blue.ogg",
    "Polar Caps, from Album 20. Slaps.ogg",
    "Polaroid, from Album 7. Gold.ogg",
    "Poppy Seed Ivy, from Album 14. Neon.ogg",
    "Pot Pie, from Album 8. White.ogg",
    "Prairie Air, from Album 15. Quest.ogg",
    "Prince Charming, from Album 20. Slaps.ogg",
    "Purple Noise, from Album 8. White.ogg",
    "Puzzled, from Album 8. White.ogg",
    "Quaint Village, from Album 15. Quest.ogg",
    "Quiet Moments with You, from Album Reflection_.ogg",
    "Radiant Vibes, from Album 1. High At The Planetarium.ogg",
    "Rain and Vibe, from Album 16. Secluded.ogg",
    "Raindrop Rhythms, from Album 18. Moonwalk.ogg",
    "Rainforest Stories, from Album 17. Electric.ogg",
    "Rainy Day Moments, from Album Secluded.ogg",
    "Ramen Nights, from Album 10. Neko.ogg",
    "Rebooting, from Album 10. Neko.ogg",
    "Red Green Blue, from Album 11. Rain.ogg",
    "Red Velvet, from Album 1Cherry Soda.ogg",
    "Reflections in Rain, from Album 18. Moonwalk.ogg",
    "Reflections on Blue Screens, from Album 8. White.ogg",
    "Regal Estate, from Album 14. Neon.ogg",
    "Remembering Tanit, from Album 9. Inu.ogg",
    "Restrained Again, from Album 19. Prime.ogg",
    "Retro Reveries, from Album 18. Moonwalk.ogg",
    "Rewind, from Album 7. Gold.ogg",
    "River Rock Fireplace, from Album 15. Quest.ogg",
    "Riverdale Express, from Album 14. Neon.ogg",
    "Rock, Water, Plant, Building, from Album 12. Cherry Soda.ogg",
    "Romantic Moments, from Album 13. Reflection_.ogg",
    "Rooftop Whispers, from Album 18. Moonwalk.ogg",
    "Rooftops, from Album 7. Gold.ogg",
    "Royal Orchard, from Album 16. Secluded.ogg",
    "Rustic Oak, from Album 14. Neon.ogg",
    "Saffron Skyline, from Album 2. Fantasy Arcade.ogg",
    "Sage Elevation, from Album 13. Reflection_.ogg",
    "Sakura, from Album 3. Sakura Dreams.ogg",
    "Salt Flats, from Album 7. Gold.ogg",
    "Samurai_s Call, from Album 3. Sakura Dreams.ogg",
    "San Andreas, from Album 7. Gold.ogg",
    "Sand Dollar, from Album 19. Prime.ogg",
    "Sandbar Beats, from Album 7. Gold.ogg",
    "Sarahtonin, from Album 8. White.ogg",
    "Satin Ripples, from Album 5. Ocularium.ogg",
    "Scam Train, from Album 6. Certain Shade Of Blue.ogg",
    "Sea Salt, from Album 19. Prime.ogg",
    "Sea Star, from Album 14. Neon.ogg",
    "Searched by the Dai Li, from Album 10. Neko.ogg",
    "Serenity in Solitude, from Album 18. Moonwalk.ogg",
    "Shadows and Echoes, from Album 18. Moonwalk.ogg",
    "Shark Fin Spotting, from Album 20. Slaps.ogg",
    "She Said, I Wonder, from Album 7. Gold.ogg",
    "Shroom Living, from Album 15. Quest.ogg",
    "Shroud_s Beard, from Album 10. Neko.ogg",
    "Sidewalk Chalk, from Album 7. Gold.ogg",
    "Signature Move, from Album 16. Secluded.ogg",
    "Silent Streets, from Album 18. Moonwalk.ogg",
    "Silhouettes in the Fog, from Album 17. Electric.ogg",
    "Silver Feather, from Album 14. Neon.ogg",
    "Simple Beauty, from Album In 4k.ogg",
    "Simple Thoughts, from Album 7. Gold.ogg",
    "Simpler, from Album 4. In 4k.ogg",
    "Singularity, from Album 1. High At The Planetarium.ogg",
    "Skipping Stones on Clouds, from Album 8. White.ogg",
    "Sky and Why, from Album 6. Certain Shade Of Blue.ogg",
    "Skyfishing, from Album 8. White.ogg",
    "Skyward, from Album 2. Fantasy Arcade.ogg",
    "Sleep Paralysis, from Album 8. White.ogg",
    "Sleeping In, from Album 10. Neko.ogg",
    "Slick Satin, from Album 16. Secluded.ogg",
    "Smooth River, from Album 6. Certain Shade Of Blue.ogg",
    "Smoothie Shack, from Album Cherry Soda.ogg",
    "Snow Drift, from Album 20. Slaps.ogg",
    "Snowcapped Mountains_, from Album 13. Reflection_.ogg",
    "Soda Stream, from Album 12. Cherry Soda.ogg",
    "Softshell, from Album 9. Inu.ogg",
    "Solace in the Basement, from Album 17. Electric.ogg",
    "Sonic Sounds, from Album 17. Electric.ogg",
    "Soul and Luna, from Album 6. Certain Shade Of Blue.ogg",
    "Soulful Shadows, from Album 18. Moonwalk.ogg",
    "Spectral Spaces, from Album 17. Electric.ogg",
    "Spring Rollin, from Album 3. Sakura Dreams.ogg",
    "Star Searcher, from Album 1. High At The Planetarium.ogg",
    "Stargaze, from Album 6. Certain Shade Of Blue.ogg",
    "Starry Garden, from Album 12. Cherry Soda.ogg",
    "Starry Night, from Album 16. Secluded.ogg",
    "Starry Solitude, from Album 18. Moonwalk.ogg",
    "Stay a While and Listen, from Album 2. Fantasy Arcade.ogg",
    "Stereophonic, from Album 7. Gold.ogg",
    "Stirling Keys, from Album 5. Ocularium.ogg",
    "Stolen Terracotta, from Album 20. Slaps.ogg",
    "Stone Walkways, from Album 19. Prime.ogg",
    "Stop It, I_m Resting, from Album 10. Neko.ogg",
    "Strands of Silver, from Album 20. Slaps.ogg",
    "Streamline, from Album 6. Certain Shade Of Blue.ogg",
    "Stuck in Wonderland, from Album 9. Inu.ogg",
    "Stuck on my Plateau, from Album Quest.ogg",
    "Suburban, from Album Gold.ogg",
    "Sudden Embrace, from Album 4. In 4k.ogg",
    "Sultry Forest, from Album 13. Reflection_.ogg",
    "Summer Heat, from Album 15. Quest.ogg",
    "Summer Night Wok, from Album Sakura Dreams.ogg",
    "Sunday Stroll, from Album 1Reflection_.ogg",
    "Sunkissed Glow, from Album 1. High At The Planetarium.ogg",
    "Sunset on Jupiter, from Album 5. Ocularium.ogg",
    "Sunset on the Shore, from Album 17. Electric.ogg",
    "Sunset Serenade, from Album 18. Moonwalk.ogg",
    "Sunshine Rain, from Album 15. Quest.ogg",
    "Sweet Dreams, from Album 8. White.ogg",
    "Swimming the English Channel, from Album 15. Quest.ogg",
    "Swiss Winters, from Album 19. Prime.ogg",
    "Take It Easy, from Album 8. White.ogg",
    "Tall Grass, from Album 2. Fantasy Arcade.ogg",
    "Tangerine, from Album 12. Cherry Soda.ogg",
    "Tapestry Thread, from Album 16. Secluded.ogg",
    "Tea Party for Two, from Album 15. Quest.ogg",
    "Tender Phobia, from Album 12. Cherry Soda.ogg",
    "Text Me Later, from Album 10. Neko.ogg",
    "The Best Way To Grow On Twitch, from Album 10. Neko.ogg",
    "The Color of Happiness, from Album 6. Certain Shade Of Blue.ogg",
    "The Darker Kind of Day, from Album 6. Certain Shade Of Blue.ogg",
    "The Depths Are Calling Me, from Album 1. High At The Planetarium.ogg",
    "The Illusive Man, from Album 2. Fantasy Arcade.ogg",
    "The Lights In The Sky Are Our Guides, from Album 1. High At The Planetarium.ogg",
    "The Mastermind, from Album 10. Neko.ogg",
    "The Phantom Follows, from Album 5. Ocularium.ogg",
    "The Quiet After the Storm, from Album 17. Electric.ogg",
    "The Round Table, from Album 13. Reflection_.ogg",
    "The Warriors Regret, from Album 3. Sakura Dreams.ogg",
    "The White Fox, from Album 6. Certain Shade Of Blue.ogg",
    "Thoughts of the Past, from Album 17. Electric.ogg",
    "Through Her Lens, from Album 7. Gold.ogg",
    "Time Keys, from Album 9. Inu.ogg",
    "Timeless Look, from Album 20. Slaps.ogg",
    "Timeless, from Album 6. Certain Shade Of Blue.ogg",
    "Tim_s Crown, from Album 10. Neko.ogg",
    "Tokyo Rain, from Album 3. Sakura Dreams.ogg",
    "Tranquility, from Album 6. Certain Shade Of Blue.ogg",
    "Trapped in Memories, from Album 5. Ocularium.ogg",
    "Trendy, from Album 4. In 4k.ogg",
    "Trips to the Moon, from Album 9. Inu.ogg",
    "Tulip Fields, from Album 15. Quest.ogg",
    "Twilight, from Album 14. Neon.ogg",
    "Twinkle Tunes, from Album 17. Electric.ogg",
    "Ultra Pure, from Album 20. Slaps.ogg",
    "Under the City Lights, from Album 17. Electric.ogg",
    "Underground, from Album 16. Secluded.ogg",
    "Unfortunate Fate, from Album 2. Fantasy Arcade.ogg",
    "Unicorn, from Album 16. Secluded.ogg",
    "Unwanted Peace, from Album 9. Inu.ogg",
    "Unwind and Recharge, from Album 8. White.ogg",
    "Up in Love, from Album 5. Ocularium.ogg",
    "Urban Twilight, from Album 18. Moonwalk.ogg",
    "Valley, from Album 10. Neko.ogg",
    "Vanilla Rain, from Album 1Neon.ogg",
    "Velvet Vistas, from Album 17. Electric.ogg",
    "Vertigo, from Album 1. High At The Planetarium.ogg",
    "Vibrant Adventures, from Album 16. Secluded.ogg",
    "Vintage Crown, from Album 16. Secluded.ogg",
    "Vintage Dreams, from Album 18. Moonwalk.ogg",
    "Viola Stems, from Album 15. Quest.ogg",
    "Virtual Soul, from Album 12. Cherry Soda.ogg",
    "Vivid Nightmares, from Album 16. Secluded.ogg",
    "Volume Up A Smidge, from Album 8. White.ogg",
    "Waiting Room, from Album 12. Cherry Soda.ogg",
    "Walkabout, from Album 4. In 4k.ogg",
    "Wandering Woodsman, from Album 18. Moonwalk.ogg",
    "Warm Chocolate Swirls, from Album 14. Neon.ogg",
    "Warm Peach, from Album 16. Secluded.ogg",
    "Warm Snow, from Album 9. Inu.ogg",
    "Warp 9, from Album 1. High At The Planetarium.ogg",
    "Watch Me Burn, from Album 16. Secluded.ogg",
    "Watching the Dance, from Album 5. Ocularium.ogg",
    "Water Lilies, from Album 12. Cherry Soda.ogg",
    "Watering the Garden, from Album 14. Neon.ogg",
    "Waves of Calm, from Album 18. Moonwalk.ogg",
    "Weathered Windmill, from Album 15. Quest.ogg",
    "Weatherman, from Album 15. Quest.ogg",
    "Weekend Warriors, from Album 13. Reflection_.ogg",
    "What a Beautiful Place, from Album 6. Certain Shade Of Blue.ogg",
    "When I Was Younger, from Album 5. Ocularium.ogg",
    "When Rolling Tides End, from Album 7. Gold.ogg",
    "When Will Never Come, from Album 9. Inu.ogg",
    "When You Were Here, from Album 4. In 4k.ogg",
    "While We Sleep, from Album 5. Ocularium.ogg",
    "Whipped Plaster, from Album 19. Prime.ogg",
    "Whispering Winds, from Album 18. Moonwalk.ogg",
    "White Cheeks, from Album 13. Reflection_.ogg",
    "White Lie, from Album 8. White.ogg",
    "White Lie, from Album Single - White Lie.ogg",
    "White Noise, from Album 5. Ocularium.ogg",
    "Wildflower Acres, from Album Neon.ogg",
    "Willow Breeze, from Album 19. Prime.ogg",
    "Windshield, from Album 10. Neko.ogg",
    "Winter Solstice, from Album 20. Slaps.ogg",
    "Wish I Was Prime, from Album 9. Inu.ogg",
    "Wisteria Way, from Album 20. Slaps.ogg",
    "Wooded Acres, from Album 16. Secluded.ogg",
    "Working Late, from Album 8. White.ogg",
    "Would You Kindly, from Album 2. Fantasy Arcade.ogg",
    "Wrong But Not Right, from Album Neko.ogg",
    "Yesterday_s News, from Album 4. In 4k.ogg",
    "Zen, from Album 3. Sakura Dreams.ogg",
    "Zinnia Whispers, from Album 19. Prime.ogg"
];
// UPDATE list_of_names_version WHEN LIST IS CHANGED!